### ISSUE TITLE
problem - uploading tft

### ISSUE THREAD

**Issue by lpt2007** [happydasch/nspanel_haui#18]
Every time I try to upload tft upload stops between 10-25%.

```
[14:52:57][W][component:237]: Component template.sensor took a long time for an operation (501 ms).
[14:52:57][W][component:238]: Components should block for at most 30 ms.
[14:52:58][W][nspanel_haui:228]: Nextion is not connected!
[14:52:58][W][component:237]: Component nspanel_haui.display took a long time for an operation (509 ms).
```

any idea?

**Comment by happydasch** [comment]
The custom component was kind of buggy. In the develop branch I switched to upstream nextion component so this should work better. You could give that code a chance. I will release a new version in a few days then this should work also.

**Comment by lpt2007** [comment]
thx, I will wait and try new release

**Comment by happydasch** [comment]
there is a new version available, this should be fixed now

**Comment by lpt2007** [comment]
I can confirm that tft upload is working:) thanks

Now I have another problem. I added light entity to `button_left_entity: light.room_youth_light_cw` but when I press button light is not turning on or off.

here is complete code:
```
###
###
###
### NSPANEL HAUI APP
###
nspanel-haui:
  module: nspanel_haui
  class: NSPanelHAUI

## panel config
  config:

## device config
    device:
      name: room_youth_switch_01
      locale: en_US
      button_left_entity: light.room_youth_light_cw
      button_right_entity: null
      show_home_button: false
      log_commands: false

## connection controller
    connection:
      heartbeat_interval: null
      overdue_factor: 2.0

## panels
    panels:
## weather panel
      - type: weather
        sleep_panel: true
        home_panel: true
        entity: weather.outside_environment_rimske_toplice
```

**Comment by lpt2007** [comment]
I just figured out that I can't see any entity, title (just empty grid with left an right arrow) and clock?

Here is code:
```
###
###
###
### NSPANEL HAUI APP
###
nspanel-haui:
  module: nspanel_haui
  class: NSPanelHAUI

## panel config
  config:

## device config
    device:
      name: room_youth_switch_01
      locale: en_US
      button_left_entity: light.room_youth_light_cw
      button_right_entity: null
      show_home_button: false
      log_commands: false

## connection controller
    connection:
      heartbeat_interval: null
      overdue_factor: 2.0

## panels
    panels:
## sleep - clock panel
      - type: clock
        entity: weather.outside_environment_rimske_toplice
        sleep_panel: true
        home_panel: false

      - type: grid
        title: LUČI
        home_panel: true
        show_power_button: false
        initial_page: 0
        entities:
          - entity: light.room_youth_light_cw
          - entity: light.room_youth_light_ww
```

any idea?
