### ISSUE TITLE
Stuck on waiting for initialization

### ISSUE THREAD

**Issue by kliko22** [happydasch/nspanel_haui#27]
I did everything to install it, but I get stuck on Waiting for Initialization!!

**Comment by happydasch** [comment]
when it is stuck on initialization then most likely the mqtt component is not setup correctly. 

check your settings, the name needs to match the name in the apps.yaml 

my config for one display:

```yaml
substitutions:
  # Heartbeat interval in seconds
  heartbeat_interval: '5'
  # Friendly name of the device
  friendly_name: 'NSPanel Guestroom'
  # Name of the device (mqtt device name should match device name,
  # use only underscore in mqtt device name)
  name: nspanel-guestroom
  mqtt_name: nspanel_guestroom
```
 part of config from apps.yaml

```yaml
nspanel-guestroom:
  module: nspanel_haui
  class: NSPanelHAUI
  config:
    device:
      name: nspanel_guestroom
      show_home_button: false
      log_commands: false
```
